spring.config.import=optional:file:./config/application-local-secrets.properties

server.address=${SERVER_ADDRESS:0.0.0.0}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/guidemate_db}
spring.datasource.username=${DB_USERNAME:ahmetkaragunlu}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
