spring.config.import=optional:file:./config/application-local-secrets.properties

server.address=${SERVER_ADDRESS:0.0.0.0}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/guidemate_db}
spring.datasource.username=${DB_USERNAME:ahmetkaragunlu}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

auth.rate-limit.register.max-per-email=${AUTH_REGISTER_MAX_PER_EMAIL:1000}
auth.rate-limit.register.max-per-ip=${AUTH_REGISTER_MAX_PER_IP:1000}
auth.rate-limit.google-login.max-per-installation=${AUTH_GOOGLE_MAX_PER_INSTALLATION:1000}
auth.rate-limit.google-login.max-per-ip=${AUTH_GOOGLE_MAX_PER_IP:1000}
