server.address=${SERVER_ADDRESS:0.0.0.0}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.springframework.security=INFO

notification.fcm.enabled=${FCM_ENABLED:true}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
