CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_by VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(320) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    auth_provider VARCHAR(20) NOT NULL,
    google_subject VARCHAR(255) UNIQUE,
    role_id BIGINT REFERENCES roles(id),
    role_selected BOOLEAN NOT NULL DEFAULT FALSE,
    account_status VARCHAR(32) NOT NULL,
    token_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_user_email ON users(email);
CREATE INDEX idx_user_account_status ON users(account_status);

CREATE TABLE confirmation_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    used_at TIMESTAMP(6) WITHOUT TIME ZONE,
    confirmed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_ct_user_id ON confirmation_tokens(user_id);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    used_at TIMESTAMP(6) WITHOUT TIME ZONE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_prt_user_id ON password_reset_tokens(user_id);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    family_id VARCHAR(36) NOT NULL,
    installation_id VARCHAR(36) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_by VARCHAR(255)
);

CREATE INDEX idx_refresh_token_family ON refresh_tokens(family_id);
CREATE INDEX idx_refresh_token_user_installation ON refresh_tokens(user_id, installation_id);
CREATE INDEX idx_refresh_token_expiry ON refresh_tokens(expires_at);

INSERT INTO roles (name, created_at, created_by)
VALUES
    ('ROLE_TOURIST', CURRENT_TIMESTAMP, 'flyway'),
    ('ROLE_GUIDE', CURRENT_TIMESTAMP, 'flyway'),
    ('ROLE_ADMIN', CURRENT_TIMESTAMP, 'flyway');
